### ISSUE TITLE
ValueError: invalid digits in Function rule_vectompz

### ISSUE THREAD

**Issue by YifanZhao0822** [xiyanghu/OSDT#1]
Hi,

I am implementing your method onto some UCI datasets and got the error message below.

```
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-309e2baaed6c>", line 158, in <module>
    bbound(X_train_osdt, y_train_osdt, lamb=lamb, prior_metric="curiosity", timelimit=timelimit, init_cart=True)
  File "/OSDT/src/osdt.py", line 415, in bbound
    x_mpz = [rule_vectompz(x[:, i]) for i in range(nrule)]
  File "/OSDT/src/osdt.py", line 415, in <listcomp>
    x_mpz = [rule_vectompz(x[:, i]) for i in range(nrule)]
  File "/OSDT/src/rule.py", line 151, in rule_vectompz
    return mpz('1' + "".join([str(i) for i in vec]), 2)
ValueError: invalid digits
```

The data formatting and test code I tried was just copied from your test_accuracy function:

```
from osdt import bbound, predict

X_train_osdt = X_train.values
y_train_osdt = y_train.values

X_val_osdt = X_val.values
y_val_osdt = y_val.values

X_test_osdt = X_test.values
y_test_osdt = y_test.values

lamb = 0.1
timelimit = 1800
leaves_c, prediction_c, dic, nleaves_OSDT, nrule, ndata, totaltime, time_c, COUNT, C_c, trainaccu_OSDT, best_is_cart, clf = \
    bbound(X_train_osdt, y_train_osdt, lamb=lamb, prior_metric="curiosity", timelimit=timelimit, init_cart=True)
_, testaccu_OSDT = predict(leaves_c, prediction_c, dic, X_test_osdt, y_test_osdt, best_is_cart, clf)
```

where the variables X/y_train/val/test are generated from sklearn.model_selection.train_test_split, thus pd.DataFrame.

Could you please help me explain what does the function rule_vectompz do and why possibly did it raise such error? Thank you so much!

**Comment by xiyanghu** [comment]
The versions we used are:
gmp 6.1.2
mpfr 4.0.1
libmpc 1.1.0
gmpy2 2-2.1.0a1

The function rule_vectompz converts a binary vector to a mpz object. And for the function mpz(str, 2), 2 indicates binary, and str is a string containing only 0 and 1. Note that the str can only contain 0 and 1, otherwise it would raise "ValueError: invalid digits".

**Comment by YifanZhao0822** [comment]
Thank you so much! It worked now.
